<a href="https://colab.research.google.com/github/Fernando-LunaP/Matematicas/blob/main/Ejercicios_4_Matem%C3%A1ticas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ejercicios 4
#Alumno: Fernando Luna Ponce

# Parte 1

Considera la matriz

<center>
$M = \begin{equation}
\begin{pmatrix}
1 & 1 & 2 & 1\\
0 & 0 & 0 & 1\\
1 & 2 & 2 & 1
\end{pmatrix}
\end{equation}$
</center>



- Sea $A$ la matriz formada con las dos primeras columnas de $M$. Describe:
  1. el dominio y el codominio de $A$ como transformación lineal.
  2. el rango de $A$ y el kernel de $A$
  3. el rango de $A^T$ y el kernel de $A^T$

  Decide  si  la  transformación $A$ es sobre, uno-a-uno, o ninguna de las dos anteriores. Además, note que claramente la tercera columna de $M$ es una combinación lineal de las dos anteriores

<center>
$col_{3} = 2col_{1} + 0col_{2}$
</center>

Encuentra esa respuesta por medio de la pseudoinversa de $A$.

Tenemos que $A = \begin{equation}
\begin{pmatrix}
1 & 1\\
0 & 0\\
1 & 2
\end{pmatrix}
\end{equation}$

1. $A : \mathbb{R}^2 \rightarrow \mathbb{R}^3$

2. Como las columnas de A son l.i. tenemos que  $Ran A = Span \{(1,0,1)^T,(1,0,2)^T\}$ y $Ker A = \{o\}$

3. Tenemos $Ran A^T = Span\{(1,1)^T, (1,2)^T\}$ y $Ker A^T = {(0, -1, 0)^T}$

In [1]:
import numpy as np
from scipy.linalg import null_space

In [2]:
At = np.array([[1, 0, 1], [1, 0, 2]])
KerAt = null_space(At)
KerAt

array([[ 0.],
       [-1.],
       [ 0.]])

Tenemos que hay un mayor número de filas que de columnas y aparte $dim (Ker A) = 0$ por lo tanto la matriz A es una transformación uno-a-uno

Tenemos que A es full column rank por lo tanto para encontrar la respuesta utilizamos la siguiente fórmula $x^+ = A^+b = (A^TA)^{-1}A^Tb$

In [3]:
A = np.array([[1, 1], [0, 0], [1, 2]])
b = np.array([[2], [0], [2]])
A_penrose = np.dot(np.linalg.inv(np.dot(A.transpose(), A)), A.transpose())
x_penrose = A_penrose.dot(b)
print(x_penrose)

[[2.]
 [0.]]


por lo tanto $Col_{3} = 2Col_{1}+0Col_{2}$

- Sea ahora $A$ la matriz formada con los dos primeros renglones de M. Describe:
  1. el dominio y el codominio de $A$ como transformación lineal.
  2. el rango de $A$ y el kernel de $A$
  3. el rango de $A^T$ y el kernel de $A^T$

  Decide si la transformación A es sobre, uno-a-uno, o ninguna de las dos anteriores. Describe al conjunto de soluciones de $Ax = b$ donde $b = (6, 0)^T$ . Puedes encontrar una solución específica $x^+$ por medio de la pseudoinversa? Hint: Las soluciones de $Ax = b$ es el conjunto:

<center>
  $x_{esp} + KerA = \{x=x_{esp} + x_{null} : x_{null} \in KerA\}$
</center>

donde $x_{esp}$ es una solución específica de $Ax = b$. ¡Este conjunto es independiente de la solución específica que se use para la descripción!

Tenemos que $A = \begin{equation}
\begin{pmatrix}
1 & 1 & 2 & 1\\
0 & 0 & 0 & 1
\end{pmatrix}
\end{equation}$

1. $A : \mathbb{R}^4 \rightarrow \mathbb{R}^2$

2. Tenemos que $dim(RanA) = 2$ y $Ran A = Span \{(1,0)^T,(1,1)^T\}$ y $Ker A = \{(-0.71, -0.42, 0.56, 0)^T, (-0.57, 0.81, -0.12, 0)^T\}$

3. Tenemos $Ran A^T = Span\{(1,1,2,1)^T, (0,0,0,1)^T\}$ y $Ker A^T = \{o\}$

In [4]:
A = np.array([[1, 1, 2, 1], [0, 0, 0, 1]])
kerA = null_space(A)
print(np.round(kerA, 2))

[[-0.71 -0.57]
 [-0.42  0.81]
 [ 0.56 -0.12]
 [-0.    0.  ]]


Como $A$ tiene más columnas que columnas que filas y $RanA \subset \mathbb{R}^2$ por lo tanto A es una transformación sobre

Tenemos que A es full row rank por lo tanto para encontrar la respuesta utilizamos la siguiente fórmula $x^+ = A^+b = A^T(AA^T)^{-1}b$

In [5]:
A = np.array([[1, 1, 2, 1], [0, 0, 0, 1]])
b = np.array([[6], [0]])
A_penrose = np.dot(A.transpose(), np.linalg.inv(np.dot(A, A.transpose())))
x_penrose = A_penrose.dot(b)
print(x_penrose)

[[1.]
 [1.]
 [2.]
 [0.]]


# Parte 2

**Demuestra que $A$ es uno-a-uno si y sólo si $A^T$ es sobre.**

Tenemos nuestra matriz $A_{nxm} = \begin{equation}
\begin{pmatrix}
a_{1,1} & a_{1,2} & \cdots & a_{1,m} \\
a_{2,1} & a_{2,2} & \cdots & a_{2,m} \\
a_{3,1} & a_{3,2} & \cdots & a_{3,m} \\
\vdots & \vdots   & \ddots & \vdots \\
a_{n,1} & a_{n,2} & \cdots & a_{n,m} \\
\end{pmatrix}
\end{equation}$ 

Supongamos que $A$ es uno-a-uno entonces $n\geq m$ y $dim (Ker A) = 0 \Rightarrow Rank A = m$

Sea $A_{m,n}^T = \begin{equation}
\begin{pmatrix}
a_{1,1} & a_{1,2} & a_{1,3} &\cdots & a_{1,n} \\
a_{2,1} & a_{2,2} & a_{2,3} & \cdots & a_{2,n} \\
\vdots & \vdots   & \vdots  & \ddots & \vdots \\
a_{m,1} & a_{m,2} & a_{m,3} & \cdots & a_{m,n} \\
\end{pmatrix}
\end{equation}$ 

Para $A^T$ tenemos que $n\geq m$, sabemos que $Rank A = Rank A^T$, $A^T: \mathbb{R}^n \rightarrow \mathbb{R}^m$ y $Rank A^T = m$ entonces $
A^T$ es sobre

Supongamos que $A$ no es uno-a-uno $\Rightarrow dim(Ker A) \neq 0$ entonces $Rank$ $A < m$, por lo que $Rank$ $A^T \neq m$, entonces $A^T$ no es sobre

Con esto demostramos que $A_{1-1} \Longleftrightarrow A^T_{sobre}$

**Prueba en una línea que $Ran A$ es ortogonal a $Ker A^T$ en el sentido que cada vector en $Ran A$ es ortogonal a cada elemento del $Ker A^T$.**

El producto punto de algún elemento del Kernel de $A^T$ con las columnas de A debe ser igual a cero, el producto punto de dos vectores ortogonales es igual a cero, por lo tanto $Ran A$ es ortogonal a $Ker A^T$.

**Prueba que si las columnas de una matriz $A$ forman un conjunto linealmente independiente entonces $A^TA$ es invertible.**

$A^TA$ es invertible si $dim(Ker A^TA) = 0$ es decir que sus columnas sean l.i. ya que entonces su determinante será 0, entonces necesitamos probar que $Ker(A^TA) = Ker A$  
Asumimos que $Ax = 0$, entonces $x$ está en el espacio nulo de $A$ y las matrices $A^TA$ y $A$ comparten el espacio nulo de la siguiente manera
<center>
$(A^TA)x = A^T(Ax)$
</center>
<center>
$ = A^T0$
</center>
<center>
$= 0$
</center>

De $A^TAx = 0$ debemos probar que $Ax = 0$, como $A$ es una matriz rectangular, no tiene inversa, pero podemos multiplicar por $x^T$ a la izquierda.
<center>
$(A^TA)x = 0$  
</center>
<center>
$x^T(A^TA)x = x^T0$  
</center>
<center>
$(x^TA^T)(Ax) = 0$  
</center>
<center>
$(Ax)^T(Ax) = 0$  
</center>
<center>
$\lVert Ax \rVert^2 = 0$  
</center>

Entonces $A^TA$ y $A$ comparten el mismo espacio nulo, entonces si $A$ tiene todas sus columnas independientes, también $A^TA$ las tendrá, en este caso $A^TA es invertible$

**Sea $ω$ un vector en $\mathbb{R}^n$ para algún $n$ y $b \in \mathbb{R}$. Considere el conjunto de todos $x$ tales que $\langle \omega, x \rangle = b$, Da una descripción geométrica de este conjunto en términos de $\omega$ y $b$.**

Se genera un hiperplano, que representa el conjunto de soluciones $x$ de una ecuación de la forma $\langle \omega, x \rangle = b$. Este hiperplano divide en dos mitades el espacio $\mathbb{R}^n$. Un hiperplano en un espacio unidimensional corresponde a un punto que divide una recta en dos partes, en una plano bidimensional corresponde a una línea que separa al plano cartesiano en dos partes, en 3 dimensiones divide el espacio en dos partes, para un espacio n-dimensional con n>3 sería simplemente llamado hiperplano. Si $b=0$ tenemos un hiperplano que pasa por el origen.

**Verifica que $Rank \; A = Rank \; A^TA = Rank \; AA^T$**

Partimos del hecho de que $Rank \; A = Rank \; A^T$ y además $Ker \; A = Ker \; A^TA \Rightarrow Rank \; A = Rank \; A^TA$  
Entonces tenemos que $Rank \; A^T = Rank \; AA^T$  
$\therefore Rank \; A = Rank \; A^TA = Rank \; AA^T$
